version: '3'
services: 
  frontend:
    build: ./holaSend
    image: "com.enigma/holasend-web"
    environment:
      - REACT_APP_API_BASE_URL=http://10.10.12.251:8080
  backend:
    build: ./api-holasend
    image: "com.enigma/holasend-api"
    restart: on-failure
    environment: 
      - DB_HOST=db
  reverse-proxy:
    build: ./reverse-proxy
    image: "com.enigma/reverse-proxy"
    restart: on-failure
    ports: 
      - "80:80"
  db:
    image: mysql
    restart: always
    environment: 
      MYSQL_DATABASE: 'holasend'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports: 
      - '3306:3306'
    expose: 
      - '3306'